### ISSUE TITLE
Problem using aip.exe on Windows: cacert.pem issue

### ISSUE THREAD

**Issue by mattytrentini** [Seeed-Studio/ardupy-aip#2]
At a guess it seems like `py2exe` has been used to package aip on Windows? It seems like it may have a problem packaging `cacert.pem`...

Same error for the `flash` and `list` commands. `board` command works fine.

```
C:\Users\mst\code\ArduPy>aip build -b wio_terminal
ERROR: Exception:
Traceback (most recent call last):
  File "site-packages\pip\_internal\cli\base_command.py", line 188, in _main
  File "aip\build.py", line 349, in run
  File "aip\build.py", line 291, in downloadAll
  File "site-packages\pip\_internal\operations\prepare.py", line 198, in unpack_url
  File "site-packages\pip\_internal\operations\prepare.py", line 124, in get_http_url
  File "site-packages\pip\_internal\operations\prepare.py", line 216, in _download_http_url
  File "site-packages\pip\_internal\network\download.py", line 189, in __call__
  File "site-packages\pip\_internal\network\download.py", line 157, in _http_get_download
  File "site-packages\pip\_vendor\requests\sessions.py", line 543, in get
  File "site-packages\pip\_internal\network\session.py", line 421, in request
  File "site-packages\pip\_vendor\requests\sessions.py", line 530, in request
  File "site-packages\pip\_vendor\requests\sessions.py", line 665, in send
  File "site-packages\pip\_vendor\requests\sessions.py", line 665, in <listcomp>
  File "site-packages\pip\_vendor\requests\sessions.py", line 245, in resolve_redirects
  File "site-packages\pip\_vendor\requests\sessions.py", line 643, in send
  File "site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
  File "site-packages\pip\_vendor\requests\adapters.py", line 416, in send
  File "site-packages\pip\_vendor\requests\adapters.py", line 228, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\mst\AppData\Local\Temp\_MEI405162\pip\_vendor\certifi\cacert.pem```

**Comment by LynnL4** [comment]
Hi, 
 It is recommended that you install ardupy aip through pip.
 ```
 pip3 install ardupy-aip
 ```
